services:
  - type: web
    name: habit-tracker-expo-web
    env: static
    buildCommand: npx expo export
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: EXPO_PUBLIC_SUPABASE_URL
        sync: false
      - key: EXPO_PUBLIC_SUPABASE_ANON_KEY
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /_expo/static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html